### ISSUE TITLE
In case of error notarize-cli cmd return success preventing CI to fail

### ISSUE THREAD

**Issue by parniere** [bacongravy/notarize-cli#1]
Hi,

During my test of notarize-cli inside github action, I ' ve seen the following case :

Sometime, request to apple server can fail. These case is detected by notarize-cli and log as error.

`Uploading file... done
Waiting for notarization status... error
Error: could not get notarization info
Error: could not notarize file`

However, it seems that the tool do not return an error code. Therefore github action flags the step as success which is problematic.

As mentionned in [git actions doc](https://docs.github.com/en/actions/creating-actions/setting-exit-codes-for-actions) , a non zero return value should work.

What do you think to improve notarize-cli by returning non zero each time of error ?

**Comment by bacongravy** [comment]
Version 0.2.0 has been published with this change.
