### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by jakepenn** [bacongravy/notarize-cli#11]
This package started failing for me -- 

```
/Users/jacobpenn/.asdf/installs/nodejs/12.14.0/.npm/lib/node_modules/notarize-cli/src/index.js:25
        console.error('Error:', error ?? 'could not upload file for notarization');
                                       ^

SyntaxError: Unexpected token '?'
```

Seems a syntax error snuck into production?

**Comment by jakepenn** [comment]
Hmm -- apologies now realizing this appears to be a strange error a this is a valid operator in javascript -- any idea why this could randomly start?

**Comment by bacongravy** [comment]
I'm guessing that this could happen if you were using a very old version of node.js -- one that was released before support for the "??" operator was added.
