### ISSUE TITLE
Fails when Apple ID is connected to multiple providers

### ISSUE THREAD

**Issue by simoncozens** [bacongravy/notarize-cli#4]
I'm part of multiple developer teams. Because of this, when I run altool from the command line, I have to pass the `--asc-provider ...` argument to choose the correct provider identity. If this isn't passed (and notarize-cli doesn't pass it), upload will fail with the following message:

> Your Apple ID account is attached to other providers. You will need to specify which provider you intend to submit content to. Please contact us if you have questions or need help.

Could there be a command line option to `notarize-cli` to select the provider?

**Comment by bacongravy** [comment]
That seems like it should be simple to do.

**Comment by jatinchowdhury18** [comment]
I ended up making a fork to implement this feature: https://github.com/jatinchowdhury18/notarize-cli/commit/0affe4fb0b674548cf8aa14d0e115e1f2f7cd638. I'm not a Javascript programmer, so my implementation may not be very good, but it seems to work for the things I've tried it on thus far.

**Comment by bacongravy** [comment]
@jatinchowdhury18 thank you for sharing! I'll see if I can get that merged back into the main project soon.

**Comment by bacongravy** [comment]
Merged [here](https://github.com/bacongravy/notarize-cli/commit/655535f8247ecb928c89e2ec16b539f40b8643cd).

**Comment by bacongravy** [comment]
Version 0.2.0 has been published with this change.
